import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import About from '../components/About'
import HomePage from '../components/Home'
import ReadMyBlog from '../components/ReadMyBlog'
import Education from '../components/Education'
import Skills from '../components/Skills'
import HomeLayout from '../components/layouts/Homelayout'
import Experience from '../components/Experience'
import Projects from '../components/Projects'
import 'bootstrap/dist/css/bootstrap.css'


export default function Home() {
  return (
    <div style={{background:"#2C001E"}}>
      <Head>
        <title>Jyoti Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/jyoti.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <link href="https://fonts.googleapis.com/css2?family=Satisfy&family=Ubuntu+Mono&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet"></link>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HomeLayout>
            <HomePage/>
            <About/>
            <Education/>
            <Skills/>
            <Projects/>
            <Experience/>
            <ReadMyBlog/>
            
      </HomeLayout>
    </div>
  )
}
